In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import entropy
import statsmodels.api as sm
import datetime
from google.colab import files
import os
import requests
import csv

In [ ]:
df1 = pd.read_csv("https://raw.githubusercontent.com/RaghavSinghal10/DS203_Project/main/Agegroup.csv")

In [ ]:
display(df1)

  AgeGroup  TotalCases Percentage
0      0-9          22      3.18%
1   Oct-19          27      3.90%
2    20-29         172     24.86%
3    30-39         146     21.10%
4    40-49         112     16.18%
5    50-59          77     11.13%
6    60-69          89     12.86%
7    70-79          28      4.05%
8     >=80          10      1.45%
9  Missing           9      1.30%

In [ ]:
df1.at[1,"AgeGroup"] = '10-19'

In [ ]:
df1.dtypes

AgeGroup      object
TotalCases     int64
Percentage    object
dtype: object

In [ ]:
count = 0
for i in df1["Percentage"]:
  df1.at[count, "Percentage"] = i[0:-1]
  count += 1

In [ ]:
df1["Percentage"] = df1["Percentage"].astype(float)

In [ ]:
display(df1)
df1.dtypes

  AgeGroup  TotalCases  Percentage
0      0-9          22        3.18
1    10-19          27        3.90
2    20-29         172       24.86
3    30-39         146       21.10
4    40-49         112       16.18
5    50-59          77       11.13
6    60-69          89       12.86
7    70-79          28        4.05
8     >=80          10        1.45
9  Missing           9        1.30

AgeGroup       object
TotalCases      int64
Percentage    float64
dtype: object

In [ ]:
df1.to_csv("AgeGroup_cleaned1.csv")

In [ ]:
files.download("AgeGroup_cleaned1.csv")

In [ ]:
df6 = pd.read_csv("https://raw.githubusercontent.com/RaghavSinghal10/DS203_Project/main/India-District-Zones.csv")

In [ ]:
display(df6)

                     District                        State        Zone
0              South Andamans  Andaman And Nicobar Islands    Red Zone
1                    Nicobars  Andaman And Nicobar Islands  Green Zone
2    North And Middle Andaman  Andaman And Nicobar Islands  Green Zone
3                     Kurnool               Andhra Pradesh    Red Zone
4                      Guntur               Andhra Pradesh    Red Zone
..                        ...                          ...         ...
728                Coochbehar                  West Bengal  Green Zone
729          Dinajpur Dakshin                  West Bengal  Green Zone
730                   Purulia                  West Bengal  Green Zone
731                Alipurduar                  West Bengal  Green Zone
732                  Jhargram                  West Bengal  Green Zone

[733 rows x 3 columns]

In [ ]:
df6.dtypes

District    object
State       object
Zone        object
dtype: object

In [ ]:
print("The number of missing entries for each variable is as follows: ")
print(df6.isnull().sum())

The number of missing entries for each variable is as follows:
District    0
State       0
Zone        0
dtype: int64

In [ ]:
df6.to_csv("India-District-Zones_cleaned.csv")
files.download("India-District-Zones_cleaned.csv")

In [ ]:
df8 = pd.read_csv("https://raw.githubusercontent.com/RaghavSinghal10/DS203_Project/main/confirmed_cases_india.csv")

In [ ]:
display(df8)

                                       state  ...  2020-09-10
0                Andaman and Nicobar Islands  ...      3426.0
1                             Andhra Pradesh  ...    527512.0
2                          Arunachal Pradesh  ...      5545.0
3                                      Assam  ...    133066.0
4                                      Bihar  ...    152192.0
5           Cases being reassigned to states  ...         0.0
6                                 Chandigarh  ...      6704.0
7                               Chhattisgarh  ...     52932.0
8                         Dadar Nagar Haveli  ...         0.0
9   Dadra and Nagar Haveli and Daman and Diu  ...      2643.0
10                               Daman & Diu  ...         0.0
11                                     Delhi  ...    201174.0
12                                       Goa  ...     22251.0
13                                   Gujarat  ...    108133.0
14                                   Haryana  ...     83353.0
15                          Himachal Pradesh  ...      8147.0
16                         Jammu and Kashmir  ...     47542.0
17                                 Jharkhand  ...     56897.0
18                                 Karnataka  ...    421730.0
19                                    Kerala  ...     95917.0
20                                    Ladakh  ...      3142.0
21                            Madhya Pradesh  ...     79192.0
22                               Maharashtra  ...    967349.0
23                                   Manipur  ...      7362.0
24                                 Meghalaya  ...      3197.0
25                                   Mizoram  ...      1192.0
26                                  Nagaland  ...      4375.0
27                                    Odisha  ...    135130.0
28                                Puducherry  ...     18084.0
29                                    Punjab  ...     69684.0
30                                 Rajasthan  ...     95736.0
31                                    Sikkim  ...      1989.0
32                                Tamil Nadu  ...    480524.0
33                                 Telangana  ...         0.0
34                              Telangana***  ...         0.0
35                                 Telengana  ...    150176.0
36                              Telengana***  ...         0.0
37                                   Tripura  ...     17252.0
38                             Uttar Pradesh  ...    285041.0
39                               Uttarakhand  ...     27211.0
40                               West Bengal  ...    190063.0

[41 rows x 226 columns]

In [ ]:
print(df8.dtypes)

state          object
2020-01-30    float64
2020-01-31    float64
2020-02-01    float64
2020-02-02    float64
               ...
2020-09-06    float64
2020-09-07    float64
2020-09-08    float64
2020-09-09    float64
2020-09-10    float64
Length: 226, dtype: object

In [ ]:
for variables in df8.columns[1:]:
  df8[variables] = df8[variables].astype(int)

In [ ]:
df8_t = df8.transpose()

In [ ]:
df8.to_csv("confirmed_cases_india_cleaned.csv")
files.download("confirmed_cases_india_cleaned.csv")

In [ ]:
df9 = pd.read_csv("https://raw.githubusercontent.com/RaghavSinghal10/DS203_Project/main/covid_19_data.csv")

In [ ]:
display(df9)

           SNo ObservationDate     Province/State  ... Confirmed  Deaths  Recovered
0            1      01/22/2020              Anhui  ...       1.0     0.0        0.0
1            2      01/22/2020            Beijing  ...      14.0     0.0        0.0
2            3      01/22/2020          Chongqing  ...       6.0     0.0        0.0
3            4      01/22/2020             Fujian  ...       1.0     0.0        0.0
4            5      01/22/2020              Gansu  ...       0.0     0.0        0.0
...        ...             ...                ...  ...       ...     ...        ...
156287  156288      11/15/2020  Zaporizhia Oblast  ...   18484.0   164.0     3021.0
156288  156289      11/15/2020            Zeeland  ...    5041.0    86.0        0.0
156289  156290      11/15/2020           Zhejiang  ...    1291.0     1.0     1279.0
156290  156291      11/15/2020    Zhytomyr Oblast  ...   22225.0   368.0    12266.0
156291  156292      11/15/2020       Zuid-Holland  ...  129188.0  2031.0        0.0

[156292 rows x 8 columns]

In [ ]:
df9 = df9.drop(["SNo"], axis=1)
df9 = df9.drop(["Last Update"], axis=1)

In [ ]:
df9["Confirmed"] = df9["Confirmed"].astype(int)
df9["Deaths"] = df9["Deaths"].astype(int)
df9["Recovered"] = df9["Recovered"].astype(int)
df9["ObservationDate"] = pd.to_datetime(df9["ObservationDate"])

In [ ]:
df9

       ObservationDate     Province/State  ... Deaths  Recovered
0           2020-01-22              Anhui  ...      0          0
1           2020-01-22            Beijing  ...      0          0
2           2020-01-22          Chongqing  ...      0          0
3           2020-01-22             Fujian  ...      0          0
4           2020-01-22              Gansu  ...      0          0
...                ...                ...  ...    ...        ...
156287      2020-11-15  Zaporizhia Oblast  ...    164       3021
156288      2020-11-15            Zeeland  ...     86          0
156289      2020-11-15           Zhejiang  ...      1       1279
156290      2020-11-15    Zhytomyr Oblast  ...    368      12266
156291      2020-11-15       Zuid-Holland  ...   2031          0

[156292 rows x 6 columns]

In [ ]:
df9.dtypes

ObservationDate    datetime64[ns]
Province/State             object
Country/Region             object
Confirmed                   int64
Deaths                      int64
Recovered                   int64
dtype: object

In [ ]:
df9.to_csv("covid_19_data_cleaned.csv")
files.download("covid_19_data_cleaned.csv")

In [ ]:
url='https://raw.githubusercontent.com/RaghavSinghal10/DS203_Project/main/ICMRTestingLabsWithCoords.csv'
response = requests.get(url)

raw_data = response.content.decode('utf-8')
raw_data = raw_data.split("\n")


with open('icmrtesting.csv', 'w') as file:
  for row in raw_data:
    file.write(row+"\n")
df_icmr = pd.read_csv("icmrtesting.csv")

In [ ]:
df_icmr

                                                   lab  ...  longitude
0    ICMR-Regional Medical Research Centre, Port Blair  ...  92.714637
1    Tomo Riba Institute of Health & Medical Scienc...  ...  93.691096
2    Sri Venkateswara Institute of Medical Sciences...  ...  79.403912
3                  Rangaraya Medical College, Kakinada  ...  82.237258
4                 Sidhartha Medical College, Vijaywada  ...  80.671323
..                                                 ...  ...        ...
262                       Tata Medical Center, Kolkata  ...  88.479632
263  Laboratory Services, Peerless Hospitex Hospita...  ...  88.394172
264  AMRI Hospitals, Department of Laboratory Medic...  ...  88.411666
265            Suraksha Diagnostics Pvt. Ltd., Kolkata  ...  88.476112
266  Dr. Lal PathLabs Ltd, Reference Laboratory, Ko...  ...  88.466851

[267 rows x 8 columns]

In [ ]:
df_icmr = df_icmr.drop(columns = ["lab","address","pincode"])
df_icmr.isnull().sum()

city         0
state        0
type         0
latitude     0
longitude    0
dtype: int64

In [ ]:
df_icmr["state"].value_counts()

Maharashtra                                 39
Tamil Nadu                                  26
Telangana                                   19
Delhi                                       18
Uttar Pradesh                               17
Karnataka                                   17
Gujarat                                     14
West Bengal                                 13
Kerala                                      12
Haryana                                     11
Madhya Pradesh                              10
Rajasthan                                    9
Odisha                                       7
Andhra Pradesh                               7
Assam                                        6
Bihar                                        6
Punjab                                       5
Jammu and Kashmir                            4
Jharkhand                                    3
Chandigarh                                   3
Himachal Pradesh                             3
Uttarakhand                                  3
Chhattisgarh                                 3
Manipur                                      2
Puducherry                                   1
Andaman and Nicobar Islands                  1
Ladakh                                       1
Sikkim                                       1
Goa                                          1
Dadra and Nagar Haveli and Daman and Diu     1
Arunachal Pradesh                            1
Mizoram                                      1
Meghalaya                                    1
Tripura                                      1
Name: state, dtype: int64

In [ ]:
df_icmr["state"] = df_icmr["state"].replace("Andaman and Nicobar Islands","Andaman and Nicobar")

In [ ]:
url2='https://raw.githubusercontent.com/RaghavSinghal10/DS203_Project/main/covid_19_india.csv'
response = requests.get(url2)

raw_data = response.content.decode('utf-8')
raw_data = raw_data.split("\n")


with open('covid_india.csv', 'w') as file:
  for row in raw_data:
    file.write(row+"\n")
df_cov_ind = pd.read_csv("covid_india.csv")

In [ ]:
df_cov_ind

       Sno      Date     Time  ...   Cured Deaths Confirmed
0        1  30/01/20  6:00 PM  ...       0      0         1
1        2  31/01/20  6:00 PM  ...       0      0         1
2        3  01/02/20  6:00 PM  ...       0      0         2
3        4  02/02/20  6:00 PM  ...       0      0         3
4        5  03/02/20  6:00 PM  ...       0      0         3
...    ...       ...      ...  ...     ...    ...       ...
8481  8482  16/11/20  8:00 AM  ...  242084   1407    257876
8482  8483  16/11/20  8:00 AM  ...   30555    364     31962
8483  8484  16/11/20  8:00 AM  ...   62543   1107     68215
8484  8485  16/11/20  8:00 AM  ...  480965   7372    511304
8485  8486  16/11/20  8:00 AM  ...  394576   7661    431551

[8486 rows x 9 columns]

In [ ]:
df_cov_ind = df_cov_ind.drop(columns = ["Sno","Time"]) 
df_cov_ind.isnull().sum()

Date                        0
State/UnionTerritory        0
ConfirmedIndianNational     0
ConfirmedForeignNational    0
Cured                       0
Deaths                      0
Confirmed                   0
dtype: int64

In [ ]:
df_cov_ind.dtypes

Date                        object
State/UnionTerritory        object
ConfirmedIndianNational     object
ConfirmedForeignNational    object
Cured                        int64
Deaths                       int64
Confirmed                    int64
dtype: object

In [ ]:
df_cov_ind["ConfirmedIndianNational"].value_counts()
df_cov_ind["ConfirmedIndianNational"] = df_cov_ind["ConfirmedIndianNational"].replace("-","0")
df_cov_ind["ConfirmedForeignNational"] = df_cov_ind["ConfirmedForeignNational"].replace("-","0")
df_cov_ind["ConfirmedForeignNational"].value_counts()

0     8354
1       39
2       36
14      25
3       12
10       6
8        5
6        3
7        3
11       2
9        1
Name: ConfirmedForeignNational, dtype: int64

In [ ]:
df_cov_ind['ConfirmedIndianNational'] = df_cov_ind['ConfirmedIndianNational'].astype(int)

In [ ]:
df_cov_ind['ConfirmedForeignNational'] = df_cov_ind['ConfirmedForeignNational'].astype(int)
df_cov_ind['Date'] =  pd.to_datetime(df_cov_ind['Date'],dayfirst= True)

In [ ]:
url3='https://raw.githubusercontent.com/RaghavSinghal10/DS203_Project/main/time_series_covid_19_confirmed.csv'
response = requests.get(url3)

raw_data = response.content.decode('utf-8')
raw_data = raw_data.split("\n")


with open('confirmed.csv', 'w') as file:
  for row in raw_data:
    file.write(row+"\n")
df_confirmed = pd.read_csv("confirmed.csv")

df_confirmed = df_confirmed.drop(columns = ["Province/State"])
df_confirmed = df_confirmed.rename(columns={"Country/Region": "Country"})

In [ ]:
df_confirmed.isnull().sum().sum()

0

In [ ]:
df_confirmed = df_confirmed.groupby("Country").sum()

In [ ]:
df_confirmed = df_confirmed.drop(columns = ["Lat","Long"])

In [ ]:
df_confirmed_1 = df_confirmed.transpose()

In [ ]:
df_confirmed_1

Country   Afghanistan  Albania  Algeria  ...  Yemen  Zambia  Zimbabwe
1/22/20             0        0        0  ...      0       0         0
1/23/20             0        0        0  ...      0       0         0
1/24/20             0        0        0  ...      0       0         0
1/25/20             0        0        0  ...      0       0         0
1/26/20             0        0        0  ...      0       0         0
...               ...      ...      ...  ...    ...     ...       ...
11/11/20        42609    25801    64257  ...   2071   17036      8667
11/12/20        42795    26211    65108  ...   2071   17056      8696
11/13/20        42969    26701    65975  ...   2072   17093      8765
11/14/20        43035    27233    66819  ...   2072   17097      8786
11/15/20        43240    27830    67679  ...   2072   17123      8829

[299 rows x 191 columns]

In [ ]:
df_confirmed_1 = df_confirmed_1.reset_index()
df_confirmed_1 = df_confirmed_1.rename(columns = {"index" : "date"})
df_confirmed_1["date"] = pd.to_datetime(df_confirmed_1["date"])
df_confirmed_1

Country       date  Afghanistan  Albania  ...  Yemen  Zambia  Zimbabwe
0       2020-01-22            0        0  ...      0       0         0
1       2020-01-23            0        0  ...      0       0         0
2       2020-01-24            0        0  ...      0       0         0
3       2020-01-25            0        0  ...      0       0         0
4       2020-01-26            0        0  ...      0       0         0
..             ...          ...      ...  ...    ...     ...       ...
294     2020-11-11        42609    25801  ...   2071   17036      8667
295     2020-11-12        42795    26211  ...   2071   17056      8696
296     2020-11-13        42969    26701  ...   2072   17093      8765
297     2020-11-14        43035    27233  ...   2072   17097      8786
298     2020-11-15        43240    27830  ...   2072   17123      8829

[299 rows x 192 columns]

In [ ]:
url4='https://raw.githubusercontent.com/RaghavSinghal10/DS203_Project/main/time_series_covid_19_deaths.csv'
response = requests.get(url4)

raw_data = response.content.decode('utf-8')
raw_data = raw_data.split("\n")


with open('deaths.csv', 'w') as file:
  for row in raw_data:
    file.write(row+"\n")
df_deaths = pd.read_csv("deaths.csv")

In [ ]:
df_deaths = df_deaths.drop(columns = ["Province/State","Lat","Long"])
df_deaths = df_deaths.rename(columns={"Country/Region": "Country"})
df_deaths = df_deaths.groupby("Country").sum()
df_deaths = df_deaths.transpose()
df_deaths = df_deaths.reset_index()
df_deaths = df_deaths.rename(columns = {"index" : "date"})
df_deaths["date"] = pd.to_datetime(df_deaths["date"])

In [ ]:
df_deaths

Country       date  Afghanistan  Albania  ...  Yemen  Zambia  Zimbabwe
0       2020-01-22            0        0  ...      0       0         0
1       2020-01-23            0        0  ...      0       0         0
2       2020-01-24            0        0  ...      0       0         0
3       2020-01-25            0        0  ...      0       0         0
4       2020-01-26            0        0  ...      0       0         0
..             ...          ...      ...  ...    ...     ...       ...
294     2020-11-11         1581      590  ...    605     350       255
295     2020-11-12         1591      598  ...    605     350       255
296     2020-11-13         1595      605  ...    605     350       257
297     2020-11-14         1605      612  ...    605     350       257
298     2020-11-15         1617      623  ...    605     353       257

[299 rows x 192 columns]

In [ ]:
url5='https://raw.githubusercontent.com/RaghavSinghal10/DS203_Project/main/time_series_covid_19_recovered.csv'
response = requests.get(url5)

raw_data = response.content.decode('utf-8')
raw_data = raw_data.split("\n")


with open('recovered.csv', 'w') as file:
  for row in raw_data:
    file.write(row+"\n")
df_recovered = pd.read_csv("recovered.csv")

df_recovered = df_recovered.drop(columns = ["Province/State","Lat","Long"])
df_recovered = df_recovered.rename(columns={"Country/Region": "Country"})
df_recovered = df_recovered.groupby("Country").sum()
df_recovered = df_recovered.transpose()
df_recovered = df_recovered.reset_index()
df_recovered = df_recovered.rename(columns = {"index" : "date"})
df_recovered["date"] = pd.to_datetime(df_recovered["date"])
df_recovered

Country       date  Afghanistan  Albania  ...  Yemen  Zambia  Zimbabwe
0       2020-01-22            0        0  ...      0       0         0
1       2020-01-23            0        0  ...      0       0         0
2       2020-01-24            0        0  ...      0       0         0
3       2020-01-25            0        0  ...      0       0         0
4       2020-01-26            0        0  ...      0       0         0
..             ...          ...      ...  ...    ...     ...       ...
294     2020-11-11        34967    12493  ...   1394   16070      8046
295     2020-11-12        35024    12574  ...   1394   16102      8060
296     2020-11-13        35036    12667  ...   1394   16134      8090
297     2020-11-14        35067    12767  ...   1394   16137      8096
298     2020-11-15        35092    12889  ...   1394   16137      8096

[299 rows x 192 columns]

In [ ]:
df_deaths.to_csv('time_series_covid_deaths.csv') 
files.download('time_series_covid_deaths.csv')
df_confirmed_1.to_csv('time_series_covid_confirmed.csv') 
files.download('time_series_covid_confirmed.csv')
df_recovered.to_csv('time_series_covid_recovered.csv') 
files.download('time_series_covid_recovered.csv')
df_cov_ind.to_csv('covid_india.csv') 
files.download('covid_india.csv')